app:
    resource: '@AppBundle/Controller/'
    type: annotation

party:
    path: /party
    defaults: { _controller: AppBundle:Party:index }

shop_add:
    path: /shop/add
    defaults: { _controller: AppBundle:Shop:addShop }

del_toy:
    path: /party/{id}/del
    defaults: { _controller: AppBundle:Party:delToy }