app:
    resource: '@AppBundle/Controller/'
    type: annotation

party:
    path: /party
    defaults: { _controller: AppBundle:Party:index }

shop:
    path: /shop
    defaults: { _controller: AppBundle:Shop:index }

shop_add:
    path: /add/shop
    defaults: { _controller: AppBundle:Shop:addShop }

del_shop:
    path: /shop/{id}/del
    defaults: { _controller: AppBundle:Shop:delete }

del_toy:
    path: /party/{id}/del
    defaults: { _controller: AppBundle:Party:delToy }