app:
    resource: '@AppBundle/Controller/'
    type: annotation

part:
    path: /party
    defaults: { _controller: AppBundle:Party:index }

shop_add:
    path: /shop/add
    defaults: { _controller: AppBundle:Shop:addShop }